# Generated by Django 3.1.3 on 2020-12-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('img', models.ImageField(upload_to='FaceImages')),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=4)),
            ],
        ),
    ]
