# Generated by Django 3.2 on 2021-05-15 12:49

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to=home.models.photo_path, verbose_name='Profile Picture')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=7)),
                ('roll_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.registeration')),
            ],
        ),
    ]
