# Generated by Django 3.2 on 2021-05-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='roll_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.registeration'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
