# Generated by Django 3.1.3 on 2020-12-12 14:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201205_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='img',
            field=models.ImageField(upload_to=home.models.photo_path, verbose_name='Profile Picture'),
        ),
    ]
