# Generated by Django 3.2 on 2021-05-15 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210515_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='roll_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
